spring.application.name=provide_old_backend
server.port=8089

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://pc-0000.rwlb.rds.aliyuncs.com:3306/        ?useSSL=true&requireSSL=false&enabledTLSProtocols=TLSv1.2&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.username=a68815
spring.datasource.password=@Xty0903